const db = require('./db');
const d = db.getDb();
const books = d.prepare("SELECT COUNT(*) as c FROM works WHERE type='book'").get();
const movies = d.prepare("SELECT COUNT(*) as c FROM works WHERE type='movie'").get();
const total = d.prepare("SELECT COUNT(*) as c FROM works").get();
console.log("Books: " + books.c);
console.log("Movies: " + movies.c);
console.log("Total: " + total.c);
console.log("\nTop 10 books by sitelinks:");
const topBooks = d.prepare("SELECT title_it, title_en, creator, year, sitelinks, genres FROM works WHERE type='book' ORDER BY sitelinks DESC LIMIT 10").all();
topBooks.forEach(w => console.log("  " + w.sitelinks + " - " + (w.title_it||w.title_en) + " (" + (w.creator||"?") + ", " + w.year + ") genres=" + w.genres));
console.log("\nTop 10 movies by sitelinks:");
const topMovies = d.prepare("SELECT title_it, title_en, creator, year, sitelinks, genres FROM works WHERE type='movie' ORDER BY sitelinks DESC LIMIT 10").all();
topMovies.forEach(w => console.log("  " + w.sitelinks + " - " + (w.title_it||w.title_en) + " (" + (w.creator||"?") + ", " + w.year + ") genres=" + w.genres));
console.log("\nBooks with genres:");
const booksWithGenres = d.prepare("SELECT COUNT(*) as c FROM works WHERE type='book' AND genres != '[]' AND genres IS NOT NULL AND genres != ''").get();
console.log("  " + booksWithGenres.c + " / " + books.c);
console.log("Movies with genres:");
const moviesWithGenres = d.prepare("SELECT COUNT(*) as c FROM works WHERE type='movie' AND genres != '[]' AND genres IS NOT NULL AND genres != ''").get();
console.log("  " + moviesWithGenres.c + " / " + movies.c);
db.close();
